### ISSUE TITLE
Stuck in Loading Player Data

### ISSUE THREAD

**Issue by IWasBorg** [johanw666/StarTrekTimelinesSpreadsheet#6]
**Describe the bug**
Your reupload functioned well until January 19th, at 11AM. After which, it's been pretty much stuck on Loading Player Data screen for almost an hour (and it still is stuck). Normally it would be stuck in Calculating Mission Success Stats for Crew for 10-20 minutes until it was ready to use. I used someone else's release only to meet the same fate; stuck on Loading Player Data for a long time. I feared Disruptor Beam changed something on the API or something else.

**To Reproduce**
1. Downloaded your release and installed it
2. Changed CLIENT_VERSION from 6.1.0 to 7.1.1
3. Ran the executable

**Expected behavior**
Should be taken to "Calculating Mission Success Stats for Crew" page for 10-20 minutes before being able to use

**Comment by johanw666** [comment]
Did you also change CLIENT_API_VERSION  to 12?

**Comment by IWasBorg** [comment]
The CLIENT_API_VERSION had already been set to 12 by the time I reinstalled and changed the CLIENT_VERSION. It was verified by unpacking the installer and checking the bundle.js file using Notepad++. The problem still stands, though.

UPDATE: It is even stranger; I tried launching the tool on another physical computer. The tool worked well, aside being stuck on "Calculating Mission Success Stats for Crew" page for 10-20 minutes like normal. So here's a question; any solutions so it would work on my own computer? I ruled out bad internet connection because Youtube worked well by the time the tool was stuck.

Another question is; where does the tool store the login data? See if I can clear the login data then log back in to try again. But I don't know where the tool stores them.

**Comment by IWasBorg** [comment]
The issue has been somewhat resolved by completely deleting the folder "Star Trek Timelines Crew Management" in AppData's Roaming folder:

C:\Users\user\AppData\Roaming\Star Trek Timelines Crew Management

After deletion, I restarted the tool, and managed to log in. Once caching and being stuck on "Calculating Mission Success Stats for Crew" page for 10-20 minutes, it brought me to a usable state.

I'll keep you posted if there are any more issues...
